---
keys:
  - &ar3s3ru C8DAE39DAA00FF97
  - &m-pa-kdw104j4r2-age age1rdvy0jjlkz9es20v63sxrhh6al9p2r3hdrwv374n7lujwhycvscqleu4je
  - &teriyaki-age age1rkmm47m39tnds8texv7zalhsl6g0s24qctag4hd0w68s9srwcfcqtnlexa
creation_rules:
  - path_regex: "machines/.*/secrets.yaml"
    key_groups: &all-machines
      - pgp:
          - *ar3s3ru
        age:
          - *m-pa-kdw104j4r2-age
          - *teriyaki-age
  - path_regex: ".*.enc.json"
    key_groups: *all-machines
